### ISSUE TITLE
Add an end game/give up/go back to main menu button

### ISSUE THREAD

**Issue by Alex-Gberg** [Alex-Gberg/projet-erasmus#16]
Give the user the option to quit the game even before it's over.

**Comment by Youjinium** [comment]
Task completed but refactoring needed to split up the source code into different folders.
Currently this code is inside Game.java in the openOptions() function

**Comment by Youjinium** [comment]
Refactoring Done. Managed to spilt up the code into different Folders.

The source code can now be found in OptionsMenu.java

And in Game.java
Line: 73-74 & 123-131
