### ISSUE TITLE
Json generator client

### ISSUE THREAD

**Issue by Bugsplatted** [Alex-Gberg/projet-erasmus#21]
The client for the Json Generator should be similar to the Guess who game.

The interface needs to be changed a bit, we need to present the user by all the possible common attributes and offer a textfield for his choices. The textfield can then be used to save the users options case-sensitively in the JSON file.

We can inspire ourselves from this : 
![image](https://user-images.githubusercontent.com/79205972/157042539-93945afc-afcd-49de-9b12-f7cee63c51c2.png)

**Comment by Alex-Gberg** [comment]
I've broken this up into several smaller issues
