### ISSUE TITLE
Solve the hard-coding for the selection box

### ISSUE THREAD

**Issue by Bugsplatted** [Alex-Gberg/projet-erasmus#33]
![image](https://user-images.githubusercontent.com/79205972/157289201-fe451589-8c5a-45a1-81ed-76d020b12265.png)

![image](https://user-images.githubusercontent.com/79205972/157289371-e502623f-e88b-4f00-9933-5eb0f817c7e0.png)

**Comment by Bugsplatted** [comment]
Let the code directly fetch the names of the options from the resources folder names.

**Comment by Alex-Gberg** [comment]
I fill the menu combo boxes with the names of the files in the JSON and newly created character_sets folders respectively.
