### ISSUE TITLE
Questions to ask the prof

### ISSUE THREAD

**Issue by Alex-Gberg** [Alex-Gberg/projet-erasmus#36]
Generator:
1. Does the user have to be able to input his own images? Or just generate a JSON based on our image sets?

Extension:
1. Is the extension/bonus mandatory?
2. When are we supposed to hand it in? (With the generator?)

Report:
1. Report page count?

Presentation:
1. What should it look like?
2. When will it take place?

Grading:
1. Are we graded on the individual hand-ins or on the final GitHub?

**Comment by Bugsplatted** [comment]
Report: page count, word count, references, format, IEEE?

**Comment by Bugsplatted** [comment]
The prof told me that they might check the github, but in our case it doesn't matter much.
Implied that they check the hand-ins.
