### ISSUE TITLE
Make the game a .exe

### ISSUE THREAD

**Issue by Alex-Gberg** [Alex-Gberg/projet-erasmus#9]
Make the game an executable program

**Comment by Youjinium** [comment]
(Settings / Preferences(on macOS) | Project Structure | Artifacts | <JavaFX-artifact> | Java FX tab | Native bundle | .exe).

**Comment by Alex-Gberg** [comment]
Not going to do this. I don't want to have to worry about stuff breaking when we move to a .exe.
